### ISSUE TITLE
Random disconnection

### ISSUE THREAD

**Issue by sw14928** [Modi1987/iiwaPy#5]
Hi,

I have been using iiwapy to control the arm and occasionally I seem to have a disconnect between the PC and the iiwa. The motion send message is seemingly not sent and the arm does not move. The MatlabToolboxServer does not disconnect either and I have to reset the iiwa. Have you encountered this problem? If so, is there a fix?

Many thanks for creating it iiwapy!

Best regards,
Sam

**Comment by Modi1987** [comment]
Hello,

I never encountered this problem. However, the firewall or an Antivirus on your PC might cause some odd behaviours, try to dissable them if they are active. Also, check the network.
Also, when you lose conection you do not have to reset iiwa, simply you can force close "MatlabToolboxServer ", then  synchronize the project to the robot again. This will reset the tcp/ip port used by KST inside the controller and you can run the "MatlabToolboxServer " again ;).

Cheers

**Comment by sw14928** [comment]
Hi,

Thank you for your suggestions. I have tried these things. I actually now suspect it is a problem with the iiwa rather than your code, as when this occurs I am unable to even move the arm in T1. I think I will need to get in touch with KUKA.

Many thanks,
Sam

**Comment by sw14928** [comment]
In fact, I am wondering - my program makes the iiwa stay still for a minute at a time, do you happen to know if it doesnt like to do this? Is there a programmed "halt" function?

Many thanks,
Sam
