### ISSUE TITLE
Arm wont move to any position

### ISSUE THREAD

**Issue by sw14928** [Modi1987/iiwaPy#7]
Hi,

I am getting an error: nak for any lin motion I am trying to make.

When I perform joint based movements, it goes to strange locations.

Do you know why this might be?

I am wondering if it is a tool I had setup, I cannot delete the tool it seems.

Many thanks,
Sam

**Comment by Modi1987** [comment]
Hello Sam,

I never encountered such problem on our robot. Also, a new tool can affect the Cartesian motion but it shall not affect the joint motion behaviour. However, I lately uploaded another pacakge compatible with [Python3.](https://github.com/Modi1987/iiwaPy3) you can try it, probably it works for you.

Cheers!

**Comment by sw14928** [comment]
Hello,

Thanks for the swift response! For some reason, no matter what I input, the arm moves to: [0,-57.3,-57.3,57.3,0,-114.6,-114.6]. It is very frustrating!

Thats awesome, I will check it out in python 3
